# Bind keys
bind("SDLK_RETURN", "$Reload")
bind("SDLK_w", "$MoveForward")
bind("SDLK_s", "$MoveBackward")
bind("SDLK_a", "$MoveLeft")
bind("SDLK_d", "$MoveRight")
bind("SDLK_q", "$MoveDown")
bind("SDLK_e", "$MoveUp")
bind("SDLK_z", "$NetworkStartSession")
bind("SDLK_x", "$NetworkJoinSession")
bind("SDLK_c", "$NetworkFindSessions")
bind("SDLK_1", "$StartSound")
bind("SDLK_2", "$StartSoundEcho")
bind("SDLK_n", "$Start3D")
bind("SDLK_m", "$End3D")

bind("SDLK_y", "$StartPath")
bind("SDLK_t", "$StartTimeline")
bind("SDLK_b", "$StartSerialize")
bind("SDLK_v", "$StartDeserialize")
