#include "ogldev_util.cpp"
#include "math_3d.cpp"
#include "pipeline.cpp"
#include "camera.cpp"
#include "glut_backend.cpp"
#include "ogldev_texture.cpp"
#include "technique.cpp"
#include "lighting_technique.cpp"
